In [7]:
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path

import os
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import pandas as pd
import seaborn as sns
import pickle as pkl
from tqdm import tqdm
import csv
from joblib import Parallel, delayed
from collections import Counter
from itertools import product
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_selection import SelectKBest, chi2, f_regression
from sklearn.model_selection import RandomizedSearchCV, train_test_split

In [4]:
with open('featurization/class_labels.pkl', 'rb') as file:
    class_labels=pkl.load(file)
class_labels = class_labels.rename(columns={"Id": "ID", "Class": "Class"})

In [5]:
class_labels

                         ID  Class
0      01kcPWA9K2BOxQeS5Rju      1
1      04EjIdbPV5e1XroFOpiN      1
2      05EeG39MTRrI6VY21DPd      1
3      05rJTUWYAKNegBk2wE8X      1
4      0AnoOZDNbPXIr2MRBSCJ      1
...                     ...    ...
10863  KFrZ0Lop1WDGwUtkusCi      9
10864  kg24YRJTB8DNdKMXpwOH      9
10865  kG29BLiFYPgWtpb350sO      9
10866  kGITL4OJxYMWEQ1bKBiP      9
10867  KGorN9J6XAC4bOEkmyup      9

[10868 rows x 2 columns]

In [9]:
# 2. 針對「ID」進行切分 (建立防火牆)
train_ids, test_ids = train_test_split(
    class_labels, 
    stratify=class_labels['Class'], 
    test_size=0.20, 
    random_state=42
)

In [12]:
train_ids

                        ID  Class
9030  AGgJTSxpu6rR8mayOhDz      8
8873  6meYANGp0FbrZU1ou3jy      8
1960  5FXu1yi9MvKsJIGPC72c      2
8004  g4EyujTPMQHLfVIRlDWS      6
6280  gp7MxT3EYbicRlBKty90      3
...                    ...    ...
1702  20oPR6DZCFTuXi3tqhev      2
6307  GTdj9ktEmJCRqwfncOQg      3
1070  FQ8hGjgtm2soB9I6bY5i      1
2773  CzgoyP4jQWJvYMn25EXS      2
5671  dh4X96NJfygBLnQSze8c      3

[8694 rows x 2 columns]

In [14]:
train_ids.to_csv("featurization/train_ids")
test_ids.to_csv("featurization/test_ids")